name: DevSecOps Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

  sbom:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Generate SBOM
      run: |
        docker run --rm -v $(pwd):/project cyclonedx/cyclonedx-cli:latest -o /project/sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v3 # Update to v3 to use Node.js 20
      with:
        name: sbom
        path: sbom.json

  sast:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Run SAST
      uses: github/codeql-action/init@v2 # Update to v2
      with:
        languages: php

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2 # Update to v2

  dast:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Start PHP server
      run: php -S localhost:8000 -t public/

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.5.0
      with:
        target: 'http://localhost:8000'
        rules-file: '.github/zap-rules.txt'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3 # Update to v3 to use Node.js 20
      with:
        name: zap-report
        path: owasp-zap-report.html
