name: DevSecOps Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

  sast:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

  dast:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to v3 to use Node.js 20

    - name: Start PHP server
      run: php -S localhost:8000

    - name: ZAP Full Scan
      id: zap-scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        token: ${{ secrets.github_token }}
        target: http://localhost:8080
